### PR TITLE
Created Teacher model

### PR DESCRIPTION
**Pull request by jashanbanga**

### CODE REVIEW

**Comment by pujanm** [comment]
Register the model to `admin.py`.

**Comment by pujanm** [comment]
@jashanbanga You can remove `teacher_id` attribute from the Teacher model. The reason is that Django automatically creates an ID attribute (Primary Key) for each and every Models that you'll create.

**Comment by jashanbanga** [comment]
But I am just naming that id as teacher_id .... it's not an extra field....
It's just that the name is changed as I checked it on the internet.

**Comment by pujanm** [comment]
1) You didn't run the black command before pushing the code. Hence, the Travis CI Build failed.
2) Can you increase the `max_length` values to say `150-200`? I feel *25* might not be enough.

**Pull request closed without merging**
